### ISSUE TITLE
your example doesn't work

### ISSUE THREAD

**Issue by someone235** [jonschlinkert/filter-values#3]
When I write this code:

	var filter = require("filter-values");

	const x = filter({a: 'a', b: 'b', c: 'c'}, function(value, key, obj) {
	  return key !== 'b';
	});

	console.log(x.b);

The output I get is: "b". I would expect it to be undefined. I guess this is because you call `isMatch(val)`, and you don't include the key in the callback arguments.

**Comment by doowb** [comment]
Looks like a bug was introduced in #2 (I believe that the `key` and `obj` should also be passed in).

If you'd like to do a PR to fix this, that'd be great!
